services:
  apuopere-backend:
    container_name: apuopere-backend
    environment:
        SPRING_API_URL: ${APP_URL_DEV}
        SPRING_DATASOURCE_URL: ${POSTGRES_URL}
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: none
        SPRING_PROFILES_ACTIVE: docker
        SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
        SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
        SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
        SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
        LLM_API_URL: ${LLM_API_URL}
        LLM_API_KEY: ${LLM_API_KEY}
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - python-embedding-service
      - apuopere-database

  python-embedding-service:
    build:
      context: ./python-embedding-service
    ports:
      - "5000:5000"

  apuopere-database:
    image: ramsrib/pgvector:15
    environment:
      POSTGRES_DB: apuope_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d apuope_db -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
