services:
  # @TODO: Database credentials should be passed as environment variables
  apuopere-backend:
    environment:
      SPRING_API_URL: ${APP_URL_DEV}
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_PROFILES_ACTIVE: docker
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: mail.apuopere@gmail.com
      SPRING_MAIL_PASSWORD: tsnbgijhjtetbonu
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      apuopere-database:
        condition: service_healthy

  # @TODO: We should use GitHub secrets to store the database credentials
  apuopere-database:
    image: postgres:15
    environment:
      POSTGRES_DB: apuope_db
      POSTGRES_USER: apuope_user
      POSTGRES_PASSWORD: apuope_password
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d apuope_db -U apuope_user"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
