/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq;


import com.apuope.apuope_re.jooq.tables.Session;
import com.apuope.apuope_re.jooq.tables.Token;
import com.apuope.apuope_re.jooq.tables.Users;


/**
 * Convenience access to all tables in apuope.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>apuope.session</code>.
     */
    public static final Session SESSION = Session.SESSION;

    /**
     * The table <code>apuope.token</code>.
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>apuope.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
