/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq;


import com.apuope.apuope_re.jooq.tables.Conversation;
import com.apuope.apuope_re.jooq.tables.Message;
import com.apuope.apuope_re.jooq.tables.MultipleChoiceQuestions;
import com.apuope.apuope_re.jooq.tables.Quiz;
import com.apuope.apuope_re.jooq.tables.QuizAnswers;
import com.apuope.apuope_re.jooq.tables.QuizResult;
import com.apuope.apuope_re.jooq.tables.Session;
import com.apuope.apuope_re.jooq.tables.TextbookEmbeddings;
import com.apuope.apuope_re.jooq.tables.Token;
import com.apuope.apuope_re.jooq.tables.Users;


/**
 * Convenience access to all tables in apuope.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>apuope.conversation</code>.
     */
    public static final Conversation CONVERSATION = Conversation.CONVERSATION;

    /**
     * The table <code>apuope.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>apuope.multiple_choice_questions</code>.
     */
    public static final MultipleChoiceQuestions MULTIPLE_CHOICE_QUESTIONS = MultipleChoiceQuestions.MULTIPLE_CHOICE_QUESTIONS;

    /**
     * The table <code>apuope.quiz</code>.
     */
    public static final Quiz QUIZ = Quiz.QUIZ;

    /**
     * The table <code>apuope.quiz_answers</code>.
     */
    public static final QuizAnswers QUIZ_ANSWERS = QuizAnswers.QUIZ_ANSWERS;

    /**
     * The table <code>apuope.quiz_result</code>.
     */
    public static final QuizResult QUIZ_RESULT = QuizResult.QUIZ_RESULT;

    /**
     * The table <code>apuope.session</code>.
     */
    public static final Session SESSION = Session.SESSION;

    /**
     * The table <code>apuope.textbook_embeddings</code>.
     */
    public static final TextbookEmbeddings TEXTBOOK_EMBEDDINGS = TextbookEmbeddings.TEXTBOOK_EMBEDDINGS;

    /**
     * The table <code>apuope.token</code>.
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>apuope.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
