/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq;


import com.apuope.apuope_re.jooq.tables.Users;


/**
 * Convenience access to all tables in apuope.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>apuope.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
