/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq.tables.records;


import com.apuope.apuope_re.jooq.tables.Message;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apuope.message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apuope.message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apuope.message.conversation_id</code>.
     */
    public void setConversationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apuope.message.conversation_id</code>.
     */
    public Integer getConversationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apuope.message.message</code>.
     */
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apuope.message.message</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apuope.message.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>apuope.message.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, Integer conversationId, String message, LocalDateTime datetime) {
        super(Message.MESSAGE);

        setId(id);
        setConversationId(conversationId);
        setMessage(message);
        setDatetime(datetime);
        resetChangedOnNotNull();
    }
}
