/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq.tables.records;


import com.apuope.apuope_re.jooq.tables.QuizAnswers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuizAnswersRecord extends UpdatableRecordImpl<QuizAnswersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apuope.quiz_answers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apuope.quiz_answers.quiz_result_id</code>.
     */
    public void setQuizResultId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.quiz_result_id</code>.
     */
    public Integer getQuizResultId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apuope.quiz_answers.question_id</code>.
     */
    public void setQuestionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.question_id</code>.
     */
    public Integer getQuestionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>apuope.quiz_answers.question_number</code>.
     */
    public void setQuestionNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.question_number</code>.
     */
    public Integer getQuestionNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>apuope.quiz_answers.answer</code>.
     */
    public void setAnswer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.answer</code>.
     */
    public String getAnswer() {
        return (String) get(4);
    }

    /**
     * Setter for <code>apuope.quiz_answers.correct</code>.
     */
    public void setCorrect(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.correct</code>.
     */
    public Boolean getCorrect() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>apuope.quiz_answers.points</code>.
     */
    public void setPoints(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>apuope.quiz_answers.points</code>.
     */
    public Integer getPoints() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizAnswersRecord
     */
    public QuizAnswersRecord() {
        super(QuizAnswers.QUIZ_ANSWERS);
    }

    /**
     * Create a detached, initialised QuizAnswersRecord
     */
    public QuizAnswersRecord(Integer id, Integer quizResultId, Integer questionId, Integer questionNumber, String answer, Boolean correct, Integer points) {
        super(QuizAnswers.QUIZ_ANSWERS);

        setId(id);
        setQuizResultId(quizResultId);
        setQuestionId(questionId);
        setQuestionNumber(questionNumber);
        setAnswer(answer);
        setCorrect(correct);
        setPoints(points);
        resetChangedOnNotNull();
    }
}
