/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq.tables.records;


import com.apuope.apuope_re.jooq.tables.QuizResult;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuizResultRecord extends UpdatableRecordImpl<QuizResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apuope.quiz_result.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apuope.quiz_result.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apuope.quiz_result.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apuope.quiz_result.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apuope.quiz_result.quiz_id</code>.
     */
    public void setQuizId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>apuope.quiz_result.quiz_id</code>.
     */
    public Integer getQuizId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>apuope.quiz_result.score</code>.
     */
    public void setScore(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>apuope.quiz_result.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>apuope.quiz_result.max_score</code>.
     */
    public void setMaxScore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>apuope.quiz_result.max_score</code>.
     */
    public Integer getMaxScore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>apuope.quiz_result.datetime</code>.
     */
    public void setDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>apuope.quiz_result.datetime</code>.
     */
    public LocalDateTime getDatetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizResultRecord
     */
    public QuizResultRecord() {
        super(QuizResult.QUIZ_RESULT);
    }

    /**
     * Create a detached, initialised QuizResultRecord
     */
    public QuizResultRecord(Integer id, Integer accountId, Integer quizId, Integer score, Integer maxScore, LocalDateTime datetime) {
        super(QuizResult.QUIZ_RESULT);

        setId(id);
        setAccountId(accountId);
        setQuizId(quizId);
        setScore(score);
        setMaxScore(maxScore);
        setDatetime(datetime);
        resetChangedOnNotNull();
    }
}
