/*
 * This file is generated by jOOQ.
 */
package com.apuope.apuope_re.jooq.tables.records;


import com.apuope.apuope_re.jooq.tables.TextbookEmbeddings;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextbookEmbeddingsRecord extends UpdatableRecordImpl<TextbookEmbeddingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>apuope.textbook_embeddings.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apuope.textbook_embeddings.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apuope.textbook_embeddings.chunk</code>.
     */
    public void setChunk(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apuope.textbook_embeddings.chunk</code>.
     */
    public String getChunk() {
        return (String) get(1);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setEmbedding(Object value) {
        set(2, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getEmbedding() {
        return get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TextbookEmbeddingsRecord
     */
    public TextbookEmbeddingsRecord() {
        super(TextbookEmbeddings.TEXTBOOK_EMBEDDINGS);
    }

    /**
     * Create a detached, initialised TextbookEmbeddingsRecord
     */
    public TextbookEmbeddingsRecord(Integer id, String chunk, Object embedding) {
        super(TextbookEmbeddings.TEXTBOOK_EMBEDDINGS);

        setId(id);
        setChunk(chunk);
        setEmbedding(embedding);
        resetChangedOnNotNull();
    }
}
