name: Build and Test Spring Boot Application

on:
  push:
    branches:
      - main
      - dev
      - feature/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Set environment variables for Docker Compose
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          LLM_API_URL: ${{ secrets.LLM_API_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
        run: |
          echo "POSTGRES_URL=${POSTGRES_URL}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${POSTGRES_USER}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> $GITHUB_ENV
          echo "LLM_API_URL=${LLM_API_URL}" >> $GITHUB_ENV
          echo "LLM_API_KEY=${LLM_API_KEY}" >> $GITHUB_ENV
          echo "SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}" >> $GITHUB_ENV
          echo "SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}" >> $GITHUB_ENV
          echo "SPRING_MAIL_HOST=${SPRING_MAIL_HOST}" >> $GITHUB_ENV
          echo "SPRING_MAIL_PORT=${SPRING_MAIL_PORT}" >> $GITHUB_ENV

      - name: Start Docker Compose
        run: docker-compose -f docker-compose.yml up -d


      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
